-- ============================================================================
-- BuildingOS Field Capture v1.3 — Database Schema
-- Run in Supabase project: MVP-mvp (ffbqtumxbtrowgaciegx)
--
-- CHANGES FROM v1.2:
--   • fc_equipment_types: added sub_types JSONB for HVAC sub-type dropdown
--   • fc_captures: added brand, sub_type, captured_by_name timestamp stamping
--   • fc_capture_photos: NEW table — multiple photos per capture (tag + unit)
--   • fc_custom_equipment_types: NEW table — user-defined equipment types
-- ============================================================================

-- 1. Field Users — people who do walks (Eric, etc.)
CREATE TABLE IF NOT EXISTS fc_users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    phone TEXT,
    role TEXT DEFAULT 'field_tech',  -- field_tech, manager, admin
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Invite Codes — generated by office user (Matt) to link field user to building
CREATE TABLE IF NOT EXISTS fc_invite_codes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code TEXT NOT NULL UNIQUE,          -- 6-char alphanumeric like "MV2024"
    building_id TEXT NOT NULL,           -- references building in main BuildingOS
    building_name TEXT NOT NULL,
    building_address TEXT,
    created_by TEXT,                     -- name of person who generated it
    max_uses INTEGER DEFAULT 10,
    uses INTEGER DEFAULT 0,
    expires_at TIMESTAMPTZ,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_fc_invite_code ON fc_invite_codes(code);

-- 3. Building Members — links field users to buildings via invite
CREATE TABLE IF NOT EXISTS fc_building_members (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES fc_users(id),
    building_id TEXT NOT NULL,
    invite_code_id UUID REFERENCES fc_invite_codes(id),
    role TEXT DEFAULT 'field_tech',
    joined_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_fc_members_building ON fc_building_members(building_id);
CREATE INDEX IF NOT EXISTS idx_fc_members_user ON fc_building_members(user_id);

-- 4. Units — populated by office user, walked by field user
CREATE TABLE IF NOT EXISTS fc_units (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    building_id TEXT NOT NULL,
    unit_name TEXT NOT NULL,
    floor TEXT,
    unit_type TEXT DEFAULT 'residential',  -- residential, common_area, mechanical, office
    sqft INTEGER,
    bedrooms NUMERIC(3,1),
    bathrooms NUMERIC(3,1),
    notes TEXT,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_fc_units_building ON fc_units(building_id);

-- 5. Equipment Types — configurable per building (Matt picks HVAC, Water Heater, Electrical Panel)
--    v1.3: added sub_types JSONB for HVAC sub-type selection (condenser, air handler, PTAC, etc.)
CREATE TABLE IF NOT EXISTS fc_equipment_types (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    building_id TEXT NOT NULL,
    name TEXT NOT NULL,                    -- "HVAC System", "Water Heater", "Electrical Panel"
    icon TEXT DEFAULT '🔧',
    description TEXT,
    sub_types JSONB DEFAULT '[]',          -- v1.3: e.g. ["Condenser","Air Handler","PTAC","Package Unit"]
    fields_config JSONB DEFAULT '[]',      -- custom fields beyond standard make/model/serial
    sort_order INTEGER DEFAULT 0,
    is_custom BOOLEAN DEFAULT false,       -- v1.3: user-created equipment type
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_fc_equip_types_building ON fc_equipment_types(building_id);

-- 6. Walk Sessions — tracks a field user's walk through the building
CREATE TABLE IF NOT EXISTS fc_walk_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    building_id TEXT NOT NULL,
    user_id UUID REFERENCES fc_users(id),
    user_name TEXT,
    status TEXT DEFAULT 'in_progress',      -- in_progress, paused, completed
    started_at TIMESTAMPTZ DEFAULT now(),
    completed_at TIMESTAMPTZ,
    units_visited INTEGER DEFAULT 0,
    captures_made INTEGER DEFAULT 0,
    notes TEXT
);
CREATE INDEX IF NOT EXISTS idx_fc_walks_building ON fc_walk_sessions(building_id);

-- 7. Unit Visits — records when a field user visits a specific unit during a walk
CREATE TABLE IF NOT EXISTS fc_unit_visits (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    walk_session_id UUID REFERENCES fc_walk_sessions(id),
    unit_id UUID REFERENCES fc_units(id),
    building_id TEXT NOT NULL,
    user_id UUID REFERENCES fc_users(id),
    status TEXT DEFAULT 'in_progress',      -- in_progress, completed, skipped, access_issue
    access_note TEXT,
    started_at TIMESTAMPTZ DEFAULT now(),
    completed_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_fc_visits_walk ON fc_unit_visits(walk_session_id);
CREATE INDEX IF NOT EXISTS idx_fc_visits_unit ON fc_unit_visits(unit_id);

-- 8. Equipment Captures — the core data: photo + AI extraction per equipment per unit
--    v1.3: added brand (distinct from make/manufacturer), sub_type
CREATE TABLE IF NOT EXISTS fc_captures (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    building_id TEXT NOT NULL,
    unit_id UUID REFERENCES fc_units(id),
    unit_visit_id UUID REFERENCES fc_unit_visits(id),
    equipment_type_id UUID REFERENCES fc_equipment_types(id),
    walk_session_id UUID REFERENCES fc_walk_sessions(id),
    captured_by UUID REFERENCES fc_users(id),
    captured_by_name TEXT,

    -- v1.3: HVAC sub-type (condenser, air handler, PTAC, package unit)
    sub_type TEXT,

    -- Photo (primary tag photo — additional photos in fc_capture_photos)
    photo_url TEXT,                         -- Supabase Storage URL
    photo_storage_path TEXT,                -- storage bucket path
    photo_filename TEXT,                    -- cleaned filename

    -- AI-extracted data
    brand TEXT,                             -- v1.3: brand name (e.g. "Goodman")
    make TEXT,                              -- manufacturer (e.g. "Daikin")
    model_name TEXT,
    model_number TEXT,
    serial_number TEXT,
    manufacture_year TEXT,
    description TEXT,
    additional_specs JSONB DEFAULT '{}',
    ai_confidence TEXT,                     -- high, medium, low
    ai_raw_response JSONB,                  -- full Claude response for debugging

    -- Human verification
    manually_verified BOOLEAN DEFAULT false,
    verified_by UUID,
    verified_at TIMESTAMPTZ,
    verification_notes TEXT,

    -- Equipment condition
    condition_rating TEXT,                  -- excellent, good, fair, poor, non_functional
    condition_notes TEXT,
    tag_readable BOOLEAN DEFAULT true,

    -- Status
    status TEXT DEFAULT 'captured',         -- captured, verified, synced_to_buildingos
    synced_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_fc_captures_building ON fc_captures(building_id);
CREATE INDEX IF NOT EXISTS idx_fc_captures_unit ON fc_captures(unit_id);
CREATE INDEX IF NOT EXISTS idx_fc_captures_type ON fc_captures(equipment_type_id);
CREATE INDEX IF NOT EXISTS idx_fc_captures_walk ON fc_captures(walk_session_id);

-- 9. Capture Photos — v1.3 NEW: multiple photos per capture (tag photo, unit photo, etc.)
CREATE TABLE IF NOT EXISTS fc_capture_photos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    capture_id UUID REFERENCES fc_captures(id) ON DELETE CASCADE,
    photo_type TEXT NOT NULL DEFAULT 'tag',  -- 'tag', 'unit', 'detail', 'condition'
    photo_url TEXT NOT NULL,
    photo_storage_path TEXT,
    photo_filename TEXT,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_fc_capture_photos_capture ON fc_capture_photos(capture_id);

-- ============================================================================
-- Row Level Security
-- ============================================================================
ALTER TABLE fc_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE fc_invite_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE fc_building_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE fc_units ENABLE ROW LEVEL SECURITY;
ALTER TABLE fc_equipment_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE fc_walk_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE fc_unit_visits ENABLE ROW LEVEL SECURITY;
ALTER TABLE fc_captures ENABLE ROW LEVEL SECURITY;
ALTER TABLE fc_capture_photos ENABLE ROW LEVEL SECURITY;

-- Service role gets full access (our backend uses service role key)
CREATE POLICY "Service role full access" ON fc_users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access" ON fc_invite_codes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access" ON fc_building_members FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access" ON fc_units FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access" ON fc_equipment_types FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access" ON fc_walk_sessions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access" ON fc_unit_visits FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access" ON fc_captures FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access" ON fc_capture_photos FOR ALL USING (true) WITH CHECK (true);

-- Grant access to roles
GRANT ALL ON fc_users TO service_role;
GRANT ALL ON fc_invite_codes TO service_role;
GRANT ALL ON fc_building_members TO service_role;
GRANT ALL ON fc_units TO service_role;
GRANT ALL ON fc_equipment_types TO service_role;
GRANT ALL ON fc_walk_sessions TO service_role;
GRANT ALL ON fc_unit_visits TO service_role;
GRANT ALL ON fc_captures TO service_role;
GRANT ALL ON fc_capture_photos TO service_role;

-- NOTE: The above policies use USING(true) because the backend connects with the
-- service_role key, which bypasses RLS entirely. For direct client access via anon
-- or authenticated roles, these should be scoped. The service_role key is never
-- exposed to the browser.

-- Restrict anon role to read-only on invite codes (needed for login flow)
-- All other tables should not be accessible to anon directly
REVOKE ALL ON fc_users FROM anon;
REVOKE ALL ON fc_building_members FROM anon;
REVOKE ALL ON fc_units FROM anon;
REVOKE ALL ON fc_equipment_types FROM anon;
REVOKE ALL ON fc_walk_sessions FROM anon;
REVOKE ALL ON fc_unit_visits FROM anon;
REVOKE ALL ON fc_captures FROM anon;
REVOKE ALL ON fc_capture_photos FROM anon;

-- Only allow authenticated users to read data for their own buildings
-- (enforced at the application level via session tokens and building membership checks)

-- Reload schema cache
NOTIFY pgrst, 'reload schema';
